// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
)

// CreateLikeInput represents a mutation input for creating likes.
type CreateLikeInput struct {
	CreateTime *time.Time
	UpdateTime *time.Time
	LikedAt    *time.Time
	UserID     int
	TweetID    int
}

// Mutate applies the CreateLikeInput on the LikeMutation builder.
func (i *CreateLikeInput) Mutate(m *LikeMutation) {
	if v := i.CreateTime; v != nil {
		m.SetCreateTime(*v)
	}
	if v := i.UpdateTime; v != nil {
		m.SetUpdateTime(*v)
	}
	if v := i.LikedAt; v != nil {
		m.SetLikedAt(*v)
	}
	m.SetUserID(i.UserID)
	m.SetTweetID(i.TweetID)
}

// SetInput applies the change-set in the CreateLikeInput on the LikeCreate builder.
func (c *LikeCreate) SetInput(i CreateLikeInput) *LikeCreate {
	i.Mutate(c.Mutation())
	return c
}
